export default {
    path:"/",
    component:()=>import("views/home"),
    name:"home",
    redirect:"welcome/recommended",
    children:[
        {
            path:'welcome/recommended',
            component:()=>import("components/recommended/"),
            name:"recommended"
        },
        {
            path:'welcome/backend',
            component:()=>import("components/backend/"),
            name:"backend"
        },
        {
            path:'welcome/frontend',
            component:()=>import("components/frontend/"),
            name:"frontend"
        },
        {
            path:'welcome/android',
            component:()=>import("components/android/"),
            name:"android"
        },
        {
            path:'welcome/ios',
            component:()=>import("components/ios/"),
            name:"ios"
        },
        {
            path:'welcome/ai',
            component:()=>import("components/ai/"),
            name:"ai"
        },
        {
            path:'welcome/freebie',
            component:()=>import("components/freebie/"),
            name:"freebie"
        },
        {
            path:'welcome/career',
            component:()=>import("components/career/"),
            name:"career"
        },
        {
            path:'welcome/article',
            component:()=>import("components/article/"),
            name:"article"
        },
    ]
}